### ISSUE TITLE
Disbursement Chart missing it's bottom axis line

### ISSUE THREAD

**Issue by felskia** [map-egypt/map-egypt.github.io#112]
<img width="449" alt="screen shot 2016-12-05 at 11 19 41 am" src="https://cloud.githubusercontent.com/assets/5421566/20892585/d1495cf4-badc-11e6-8c89-a18b95bd2fd3.png">

**Comment by ascalamogna** [comment]
@felskia do you know what page this is on?

**Comment by felskia** [comment]
@ascalamogna it's here: https://map-egypt.github.io/#/en/projects/2f1586ac-a460-4d52-96b3-f9319b805daf?_k=jepz2j

**Comment by ascalamogna** [comment]
@dereklieu I get an error for the x2 value for this

**Comment by ascalamogna** [comment]
@dereklieu can you take a look at this?
