### ISSUE TITLE
Adding Additional Filters

### ISSUE THREAD

**Issue by felskia** [map-egypt/map-egypt.github.io#113]
We'll need to add in SDG goals and also I would guess Project Type will be important, which would filter on Active, Past and Planned.

**Comment by dereklieu** [comment]
@felskia I don't see the project type anywhere in the project data, either in the list or detail endpoints. cc @kamicut

**Comment by kamicut** [comment]
@felskia @dereklieu Is this referring to project status? There is a `status` attribute in the data

**Comment by felskia** [comment]
@dereklieu ignore the project type for now. It was in the wireframes. I'll see if we still need it. One thing to note though, some of the filters that were there before aren't showing up now.

**Comment by dereklieu** [comment]
That's fixed in my PR.
