### ISSUE TITLE
Project Filter Modal 

### ISSUE THREAD

**Issue by felskia** [map-egypt/map-egypt.github.io#114]
To accommodate additional filters and also lists as more things get added what do you think about condensing some of the lists. Maybe:

- making the font size smaller
- putting a max height on lists and having them scroll. 

This way you could probably fit three across. FYI we'll probably need to add SDG goals to this as well.

**Comment by ascalamogna** [comment]
@felskia is the arabic still going to be part of the label? I'm worried if we do three across we'll have to cut off some of the labels due to width.

**Comment by felskia** [comment]
@ascalamogna no more arabic. :) Once the language transition is implement there should be no more arabic on the English side.
