### ISSUE TITLE
Locations not working on Individual Project page

### ISSUE THREAD

**Issue by felskia** [map-egypt/map-egypt.github.io#126]
Hagar added a new project with many location and they show up as --. See https://map-egypt.github.io/#/en/projects/13f7fd00-a53f-4566-a771-f9de5f73fc81?_k=s2gxtd

Not sure if it's a problem on the backend or not so assigning it to both @kamicut and @dereklieu

**Comment by dereklieu** [comment]
Wow this must have a ton of districts.

Right now we have no support for districts, so any district id's show up as '--'.
