### ISSUE TITLE
Make a sample of what district level data should look like

### ISSUE THREAD

**Issue by felskia** [map-egypt/map-egypt.github.io#128]
Make a sample for this so that they know what it should look like. For indicator data.

**Comment by drewbo** [comment]
@felskia how are we handling district level data (as opposed to governorate)

**Comment by felskia** [comment]
@drewbo we'll add in the district level shapefiles and match them to these numbers: https://docs.google.com/spreadsheets/d/1akNaDYth_rHErlhz0zsNAddYZgdkPmu4afVxkqYlAek/edit?usp=sharing (second tab) 

Let me know if this doesn't make sense.

**Comment by drewbo** [comment]
Should the user have to select whether they are inputting district or governorate data (in which case we need another field) or should we auto-detect based on the field names?

cc: @kamicut @dereklieu

**Comment by dereklieu** [comment]
I think if data is tied to a district or governorate, then the name of that district or governorate should come from a dropdown to reduce user error. 

Auto-detecting also runs the risk of someone trying to enter a mix of district and governorate data in the same row.

I would support making someone choose first, ala adding the new field.

**Comment by drewbo** [comment]
Uploaded an example csv at: https://map-egypt.github.io/admin/#/indicators/0d476d98-c632-499a-8615-44ca19ea8046?_k=1lko71

**Comment by drewbo** [comment]
@dereklieu there will still be the possibility of matching errors via input (we're not validating each data point matches to a given id) but I'll create a separate ticket for adding "data geo level" to the admin options
