### ISSUE TITLE
Project status

### ISSUE THREAD

**Issue by felskia** [map-egypt/map-egypt.github.io#129]
Projects look as if they're all delayed but they're not. 

@kamicut @dereklieu don't know where the issue lies so assigned you both.

**Comment by dereklieu** [comment]
On the left side is planned, on the right side is actual. So it looks like every project either has no actual end date, or has a later end date than planned. @felskia should we not call it delayed if there's no end date?

![screen shot 2017-01-09 at 1 10 11 pm](https://cloud.githubusercontent.com/assets/1590802/21777525/31e6ad36-d66d-11e6-909b-06241c44a15c.png)

**Comment by felskia** [comment]
@dereklieu she was talking about instances like the "Advanced Marketing and Agribusiness Logistics" project. The projected start date is the same as the actual start date, so they're not delayed.

**Comment by dereklieu** [comment]
Ok, here's a proposal for how this could work

1. if there are actual and planned end dates, first use that.
2. if there's no actual end date but a planned end date that's later than today, use actual and planned *start* dates
3. at this point, it's on time if the actual is equal to or less than the planned date. if actual is later or actual or planned is missing, it's delayed.

**Comment by felskia** [comment]
@dereklieu yes, I think that works and makes sense.
