### ISSUE TITLE
Food insecurity indicator isn't showing up

### ISSUE THREAD

**Issue by felskia** [map-egypt/map-egypt.github.io#130]
Under other indicators > agriculture > food insecurity. When you click and add this indicator, it doesn't show up on the map.

**Comment by drewbo** [comment]
It "appears" but all the values are `NaN` and get colored the lowest value. We should check the handling of non-numerical values.

<img width="444" alt="screen shot 2016-12-20 at 5 56 42 pm" src="https://cloud.githubusercontent.com/assets/7108211/21371167/b1c14f24-c6dd-11e6-8037-914c4526a5ed.png">

**Comment by felskia** [comment]
But there are values in the backend. They're just categorical
