### ISSUE TITLE
Hover for map points

### ISSUE THREAD

**Issue by felskia** [map-egypt/map-egypt.github.io#134]
Right now the hover is a little strange, the line behind the circle. Let's see if we can do something else here.

**Comment by ascalamogna** [comment]
@dereklieu @nbumbarger do you know where this is being created? I can't recreate it in the inspector tools. 
<img width="469" alt="screen shot 2017-01-10 at 2 49 37 pm" src="https://cloud.githubusercontent.com/assets/6752098/21822135/0cb3a578-d744-11e6-899a-177665aa24cf.png">

**Comment by nbumbarger** [comment]
Mapbox [automatically](https://github.com/map-egypt/map-egypt.github.io/blob/develop/app/assets/scripts/components/map.js#L156) shows the area of points that make up a cluster. You can style the hover effect like you would like any other polygon using a `polygonOptions` property, or you could hide it like this:
```
this.markerLayer = L.markerClusterGroup({
  polygonOptions: {
    opacity: 0,
    fillOpacity: 0
  }
});
```
