### ISSUE TITLE
Pages for ministry and responsible project owner

### ISSUE THREAD

**Issue by felskia** [map-egypt/map-egypt.github.io#146]
We need two additional pages, I'm pretty sure @ascalamogna stated building out a page for these since they use a very similar template.

@kamicut can you double-check to see that the `responsible_party` field is getting sent as a field?

**Comment by kamicut** [comment]
there's a `responsible_ministry` attribute as well as `local_manager` and `local_manager_ar`. Are these the same @felskia ?

**Comment by felskia** [comment]
@kamicut they're not the same so that sounds good. Thanks!

**Comment by dereklieu** [comment]
@ascalamogna can you lay out these pages? I can help you get set up with putting them in the router if that's helpful.

**Comment by nbumbarger** [comment]
added in https://github.com/map-egypt/map-egypt.github.io/pull/154
