### ISSUE TITLE
Fix Arabic Language Pages

### ISSUE THREAD

**Issue by felskia** [map-egypt/map-egypt.github.io#161]
When you click on arabic in the main header, it should stay on the same page and just flip the page. Right now it goes back to the homepage.

**Comment by nbumbarger** [comment]
@kamicut Can this be fixed? I'm going to need some guidance in using the router, if so.

**Comment by felskia** [comment]
It can be, we did it on IOD. @dereklieu might know or if not we can consult Alireza since he did it on IOD

**Comment by dereklieu** [comment]
@nbumbarger you can easily do this by changing this links. No need to touch the router.

https://github.com/map-egypt/map-egypt.github.io/blob/develop/app/assets/scripts/components/page-header.js#L56

from naive `/en` and `/ar` to something that represents the current location. 

You can get the current location as a prop, and it's already being used in the page header = see [here](https://github.com/map-egypt/map-egypt.github.io/blob/develop/app/assets/scripts/components/page-header.js#L58).

You would just need to replace the current language path with the target language.
