### ISSUE TITLE
Project status markers on maps

### ISSUE THREAD

**Issue by felskia** [map-egypt/map-egypt.github.io#163]
Right now these are grey and should be the color that they appear everywhere else. 
<img width="541" alt="screen shot 2017-01-12 at 11 04 08 am" src="https://cloud.githubusercontent.com/assets/5421566/21897220/f4ee6a44-d8b6-11e6-9ec5-2131907deda3.png">

**Comment by ascalamogna** [comment]
@dereklieu @nbumbarger can you look into this?
