### ISSUE TITLE
Issues with circular map markers

### ISSUE THREAD

**Issue by felskia** [map-egypt/map-egypt.github.io#164]
Right now the circles aren't aligned with each other. 

<img width="360" alt="screen shot 2017-01-12 at 10 57 51 am" src="https://cloud.githubusercontent.com/assets/5421566/21897391/6e4f3c7e-d8b7-11e6-80c9-546c2d7920b0.png">

@dereklieu @nbumbarger I know nick has more time so if he can do this task that would be great.

**Comment by dereklieu** [comment]
Think this is a css issue, @ascalamogna could you take a look?

**Comment by dereklieu** [comment]
Seems fixed from my end.
