### ISSUE TITLE
List view graphs - Projects and Indicators page

### ISSUE THREAD

**Issue by felskia** [map-egypt/map-egypt.github.io#17]
For indicators that have been selected the most ideal solution would be to visualize them in a graph together. If this isn't possible probably making long tall graphs would be ideal and putting them side by side.

**Comment by drewbo** [comment]
@felskia Is there a separate page for Indicators or are they only viewable on the map (and only one at a time)

**Comment by felskia** [comment]
@drewbo they're on the list view page - the toggle that's on the map page.
