### ISSUE TITLE
Super thin line above funding number on project cards

### ISSUE THREAD

**Issue by felskia** [map-egypt/map-egypt.github.io#173]
<img width="556" alt="screen shot 2017-01-12 at 11 57 37 am" src="https://cloud.githubusercontent.com/assets/5421566/21899491/62f943e0-d8be-11e6-949e-ad32d215021f.png">

This also appears at the top of a project page. 
<img width="386" alt="screen shot 2017-01-12 at 12 17 34 pm" src="https://cloud.githubusercontent.com/assets/5421566/21900268/3144fb5c-d8c1-11e6-9869-d624d2c41c1d.png">

**Comment by ascalamogna** [comment]
@felskia I don't see this at all, what browser are you using?

**Comment by felskia** [comment]
Chrome. Although I no longer see them. :)
