### ISSUE TITLE
Indicator graphs on project list view

### ISSUE THREAD

**Issue by felskia** [map-egypt/map-egypt.github.io#176]
There are a few issues: 

- the values on the charts right now are the governorate numbers not the names like "Cairo". This needs to be fixed on the chart and the hover. 

- The charts will need to flip, being vertical instead of horizontal. So that we can actually show labels without them overlapping and being unreadable.

**Comment by nbumbarger** [comment]
Fixed by https://github.com/map-egypt/map-egypt.github.io
