### ISSUE TITLE
Consistency of map keys

### ISSUE THREAD

**Issue by felskia** [map-egypt/map-egypt.github.io#181]
Sometimes they are at the top of the map, most of the time on the bottom left hand corner. Sometimes they are in a transparent box on top of the map, sometimes not. I would just make that consistent, esp true here on the category page. 

<img width="423" alt="screen shot 2017-01-12 at 12 25 41 pm" src="https://cloud.githubusercontent.com/assets/5421566/21900596/6db2a1ec-d8c2-11e6-8bd6-6d93c0ddf6cf.png">

**Comment by ascalamogna** [comment]
@felskia which page is this showing up on?

**Comment by felskia** [comment]
It was on an individual category page.
