### ISSUE TITLE
Category page label change

### ISSUE THREAD

**Issue by felskia** [map-egypt/map-egypt.github.io#182]
Further down I think the label should be "Agro-industry, Marketing & Trade Projects" instead of just projects or whatever category page you're on.

**Comment by ascalamogna** [comment]
@nbumbarger @dereklieu this title is coming from projects-list.js. Can one of you look into it? I think this is just used on the category pages but I'm not sure

**Comment by ascalamogna** [comment]
@felskia Since this is a little more complicated to change could we say 'Associated Projects' or something?

**Comment by felskia** [comment]
@ascalamogna my fear is that people might think they're related projects...
