### ISSUE TITLE
Locations for one project are being duplicated

### ISSUE THREAD

**Issue by felskia** [map-egypt/map-egypt.github.io#188]
<img width="311" alt="screen shot 2017-01-12 at 1 13 57 pm" src="https://cloud.githubusercontent.com/assets/5421566/21902220/1473179a-d8c9-11e6-9c3f-e84213cc4998.png">

**Comment by nbumbarger** [comment]
@felskia I don't think this is a bug- at least not on the site. The record seems to be stored with the duplicated attributes.
