### ISSUE TITLE
Adding space in between district/governorate locations

### ISSUE THREAD

**Issue by felskia** [map-egypt/map-egypt.github.io#189]
When there is a grouping of district + governorate is there a way to add space between that grouping and the next one? That way it might be easier to see what is grouped with what. 

<img width="290" alt="screen shot 2017-01-12 at 1 15 13 pm" src="https://cloud.githubusercontent.com/assets/5421566/21902285/56140826-d8c9-11e6-897a-8151d00fbade.png">

**Comment by ascalamogna** [comment]
@dereklieu I don't know if this is possible?

**Comment by dereklieu** [comment]
Hm, I think we can do this, you can assign this to me.
