### ISSUE TITLE
Develop timelines 

### ISSUE THREAD

**Issue by felskia** [map-egypt/map-egypt.github.io#19]
Visualize current and proposed timelines - you can see these at the top of the project page, project owner pages, and also ministry pages. Project pages are the most relevant. Right now the data doesn't have ministry and project owner datapoints.

**Comment by dereklieu** [comment]
This is still blocked on the data side isn't it? I see `created_at` and `updated_at` fields coming from the API but it doesn't seem like those are the ones to use.

**Comment by dereklieu** [comment]
These are up on the `project-detail` branch, need some styling love from @ascalamogna. Switching assignment over.
