### ISSUE TITLE
Project components

### ISSUE THREAD

**Issue by felskia** [map-egypt/map-egypt.github.io#190]
<img width="605" alt="screen shot 2017-01-12 at 1 16 50 pm" src="https://cloud.githubusercontent.com/assets/5421566/21902327/8a4ff7c6-d8c9-11e6-8e60-f45353d41174.png">

When there aren't certain components on an individual project page, please remove these sections from the page. Example above is KMI and also Project link

**Comment by nbumbarger** [comment]
fixed in https://github.com/map-egypt/map-egypt.github.io/tree/chart-fixes
