### ISSUE TITLE
RTL issues continued

### ISSUE THREAD

**Issue by felskia** [map-egypt/map-egypt.github.io#191]
Charts should be flipped: 
<img width="469" alt="screen shot 2017-01-12 at 1 20 42 pm" src="https://cloud.githubusercontent.com/assets/5421566/21902520/394c9964-d8ca-11e6-8d48-96d617edbacb.png">

Sort by text is really high
<img width="357" alt="screen shot 2017-01-12 at 1 21 45 pm" src="https://cloud.githubusercontent.com/assets/5421566/21902525/3d154640-d8ca-11e6-84c0-39aecba7e1d2.png">

Search box - the text starts in the middle of the input box and also the rounded corners are off.
<img width="421" alt="screen shot 2017-01-12 at 1 21 37 pm" src="https://cloud.githubusercontent.com/assets/5421566/21902541/46e564c0-d8ca-11e6-8abd-9c0489e8d728.png">

**Comment by ascalamogna** [comment]
@dereklieu I think it's really difficult or time consuming to flip the charts right?

**Comment by ascalamogna** [comment]
@nbumbarger can you flip the charts here? Everything else has been taken care of.

**Comment by nbumbarger** [comment]
Closed by https://github.com/map-egypt/map-egypt.github.io/pull/225
