### ISSUE TITLE
Make indicator tables a little bigger

### ISSUE THREAD

**Issue by felskia** [map-egypt/map-egypt.github.io#202]
<img width="1117" alt="screen shot 2017-01-13 at 5 48 06 pm" src="https://cloud.githubusercontent.com/assets/5421566/21948332/7d882816-d9b8-11e6-83b7-bc80e68cc1ff.png">

**Comment by ascalamogna** [comment]
@felskia I think this might be difficult because some charts have only a few bars while others like this one have a lot and the height is set to be the same for all. @dereklieu is there a good way to account for this?

**Comment by dereklieu** [comment]
Yeah, all the charts are assigned the same height. At least the majority of indicators though should be at the district level, so maybe we should just add some height to this standard size?
