### ISSUE TITLE
Stats on homepage

### ISSUE THREAD

**Issue by felskia** [map-egypt/map-egypt.github.io#205]
For right now since they're not sure what stats they want to put on the page, they just want: 

- total number of beneficiaries
- the total amount of funds 
- number of donors

Maybe @ascalamogna hide the style of the percentage stats with the projects underneath and just add in these numbers for now.

**Comment by ascalamogna** [comment]
@felskia do you know what these numbers are? Shouldn't they come from the data?

**Comment by ascalamogna** [comment]
@nbumbarger can you add these numbers to the homepage where the percent stat are and I can style them?

**Comment by nbumbarger** [comment]
@ascalamogna [This branch](https://github.com/map-egypt/map-egypt.github.io/tree/homepage-stats) adds totalProjects, totalDonors, and totalFunding variables to the view/home.js page, which can be inserted into the layout as e.g. `{totalProjects}`.

**Comment by ascalamogna** [comment]
@nbumbarger I think we're going to need to format the funding number to something like 4.1M or something. Can you do this?

**Comment by dereklieu** [comment]
There are a number of helper functions in `utils/format` that do exactly this.
