### ISSUE TITLE
Indicator legend fixes

### ISSUE THREAD

**Issue by felskia** [map-egypt/map-egypt.github.io#206]
Right now, some categories aren't sorting correctly. You can see this if you select Other Indicators > Health > Food Insecurity - 2011. The order isn't correct. 

Also, we need to add in Unit into the key. 

@nbumbarger assigned to you but let me know if I should assign to someone else.

**Comment by nbumbarger** [comment]
@felskia @kamicut 
`Food Insecurity - 2001` doesn't have numerical values- its values are `low`, `medium`, and `high`. I could add a special case to convert these values to 1, 2, and 3, but there are probably other exceptions yet to discover. Should we drop non-numerical categories?
Also, units for various categories don't appear to be exposed in the API. Do we even have access to them?

**Comment by felskia** [comment]
@nbumbarger @kamicut we need to have these categorical categories. They're required

**Comment by nbumbarger** [comment]
So, should I convert 'low', 'medium', and 'high' to 1, 2, 3 in real time? Are there going to be any other categorical metrics?

**Comment by felskia** [comment]
@nbumbarger @kamicut It's really the other way around. When there is text, they want the text. Hagar was going to go in and change the 1 2 3 to High Med Low. If those are hard to put in order, do we need another input field in the admin that let's users input the order?

**Comment by nbumbarger** [comment]
I don't think I understand... I'm talking about the numbers that drive the chart behind the scenes. Should we not chart values when they're categorical?
