### ISSUE TITLE
Note issues with log in 

### ISSUE THREAD

**Issue by felskia** [map-egypt/map-egypt.github.io#211]
Note how to produce this so that we can see whether or not it is an issue on our end or an issue that the public will see.

**Comment by nbumbarger** [comment]
This isn't the issue I was thinking of from OAM. I can't log on to the remote site in any way (only a locally running version), so it does seem to be an issue that will affect the public but I can't isolate the cause. cc @kamicut

**Comment by drewbo** [comment]
@nbumbarger do you have any ad-blockers running? This caused a problem for me. There are also occasional re-logins required when switching between admin + front-end and refreshing a lot but I'm not sure that will be a common user workflow

**Comment by nbumbarger** [comment]
I can't log on using Firefox with no extensions. I have Chrome running with several extensions, but no add blockers.
