### ISSUE TITLE
Make .md file for about page

### ISSUE THREAD

**Issue by felskia** [map-egypt/map-egypt.github.io#215]
Just need a page that the client will be able to edit

@ascalamogna is this something you might be able to do?

**Comment by felskia** [comment]
@dereklieu didn't reassign the ticket because we talked about this this morning but again just making an HTML page for the about page.

**Comment by dereklieu** [comment]
@felskia the snippets are [here](https://github.com/map-egypt/map-egypt.github.io/tree/develop/app/assets/scripts/about).
