### ISSUE TITLE
Look at map indicator colors

### ISSUE THREAD

**Issue by felskia** [map-egypt/map-egypt.github.io#250]
Comment from Hagar:

(Although I like the style of how the indicator data appears) Show more apparent/brighter colors for the indicators (like the indicator food insecurity) – since the differences between classes is not very apparent, and since shades of blue for both the website and indicators makes the contrast too subtle.

**Comment by felskia** [comment]
@ascalamogna I don't know if you have time for one last thing. If you don't let me know.

**Comment by felskia** [comment]
@ascalamogna let me know if you might have time to look at this tomorrow or Wednesday. We want to get this wrapped up in the next few days. Thanks!

**Comment by ascalamogna** [comment]
@felskia I won't have time to look at this until the end of the week.
