### ISSUE TITLE
Additional info - Project stats

### ISSUE THREAD

**Issue by felskia** [map-egypt/map-egypt.github.io#251]
Add if the funds are loans vs grants or both, and add that to overview stats

**Comment by felskia** [comment]
Big numbers at the bottom of this screenshot

<img width="1121" alt="screen shot 2017-02-01 at 3 24 50 pm" src="https://cloud.githubusercontent.com/assets/5421566/22524783/a1a435f8-e892-11e6-87d5-b21518bffd09.png">

**Comment by nbumbarger** [comment]
This doesn't seem to be in the metadata. @kamicut @dereklieu, am I missing something?

**Comment by dereklieu** [comment]
I remember there being an array of funding sources that we combine to make the funding number. Each item in that array specifies whether it's a loan or grant. This is as much as I remember without looking into the code myself.

**Comment by nbumbarger** [comment]
@dereklieu The array looks like this, for each project:
```
{ donor_name: "IFAD",
  fund: {
    amount: 71000000,
    currency: "USD",
    original: 71000000,
    rate: 1
  }
}
```
Is the load/ grant tag encoded in the `rate` attribute?

**Comment by dereklieu** [comment]
Hm weird I thought this used to be there. @kamicut any idea?

**Comment by kamicut** [comment]
@nbumbarger @dereklieu it's in the disbursed funds object, e.g in "Farm-Level Irrigation Modernization" 
```js
    "disbursed": [
      {
        "date": "2016/10",
        "fund": {
          "rate": 1,
          "amount": 45620000,
          "currency": "USD",
          "original": 45620000
        },
        "type": {
          "ar": "قرض",
          "en": "Loan"
        },
        "donor_name": "World Bank"
      }
    ],
```

**Comment by felskia** [comment]
@nbumbarger I don't see this change anywhere. Could you direct me to where this is? 

Thanks!

**Comment by nbumbarger** [comment]
@felskia Whoops, I mistook this ticket for the one adding stats to the homepage.

**Comment by nbumbarger** [comment]
@felskia Actually, it was added- I forgot that those attributes are extremely rare. Here's an [example](https://map-egypt.github.io/#/en/projects/2f1586ac-a460-4d52-96b3-f9319b805daf?_k=ahgznt) of a project with loans represented (when you're logged in). On a page with grants available, they would appear as well.
