### ISSUE TITLE
Some charts on category pages are not flipped to rtl

### ISSUE THREAD

**Issue by felskia** [map-egypt/map-egypt.github.io#255]
Second set of charts are not flipped: 
<img width="1038" alt="screen shot 2017-02-06 at 11 40 27 am" src="https://cloud.githubusercontent.com/assets/5421566/22665254/1a89000a-ec82-11e6-9c51-ed83bfe081d7.png">

**Comment by dereklieu** [comment]
It's possible these aren't getting passed the `lang` property @nbumbarger.
