### ISSUE TITLE
Add additional homepage stat

### ISSUE THREAD

**Issue by felskia** [map-egypt/map-egypt.github.io#260]
Add to overview statistics "donor synergies" number of collaboration between donors – and name of donors collaborating

Anytime there are multiple donors that should count as 1 collaboration. But this shouldn't count if it's the Government that is chipping in money. So for example:

Project 1: World Bank, IFAD  =  1 collaboration
Project 2: World Bank, Gov of Egypt = 0 collaborations 

@dereklieu @nbumbarger this is the last issue they wanted to see if we could add in their list of changes they sent over a few weeks ago. Didn't know who might have time to do it. Let me know. 

Thanks!

**Comment by nbumbarger** [comment]
@felskia What happens when a project has more than 2 collaborators?
Is World Bank, IFAD, Italian Debt Swap still 1 collaboration? 2? 3?
Is World Bank, IFAD, Gov of Egypt still 0 collaborations?

**Comment by nbumbarger** [comment]
I also need more details on how to display collaborating donors.
Should each collaboration get a mention (allowing some donors to be mentioned multiple times)?
```
World Bank, IFAD, Italian Debt Swap
USAID, IFAD
Project Beneficiaries, World Bank, USAID
```
Should we just list every organization that has been involved in one or more collaborations?
```
World Bank
USAID
IFAD
Italian Debt Swap
Project Beneficiaries
```
Should this big list be centered under the charts, or somewhere else? Is there a cutoff to how many collaborators or collaborations can be shown?

**Comment by felskia** [comment]
@nbumbarger from my understanding it would be this: 

World Bank, IFAD, Italian Debt Swap =  1 collaborations
World Bank, IFAD, Gov of Egypt = 1 collaborations
World Bank, Gov of Egypt = 0 collaborations

Also... I would say to just list them out like this: 

World Bank
USAID
IFAD
Italian Debt Swap
Project Beneficiaries

Because if you list them out the other way, you'd want to see what project they're associated with. 

I can ask Hagar all of these questions though, just to make sure. Let me know if you'd prefer that. 

Also, as far as positioning goes, maybe we can put it below the first row of big numbers and have the  donor names run horizontally? I might ask @ascalamogna for her input here as well. 

Thanks!

**Comment by nbumbarger** [comment]
@ascalamogna while I hook this up, can you add a mock list, like Ali has above, to the homepage layout?
