### ISSUE TITLE
Implement Palestine Map

### ISSUE THREAD

**Issue by felskia** [map-egypt/map-egypt.github.io#277]
Got the ok for Hagar. Please implement this map as you have it mocked up. Thanks!

**Comment by DylanMoriarty** [comment]
[Published with it added](https://api.mapbox.com/styles/v1/map-egypt/civld9uy0000n2kmnd7lqs3ne.html?title=true&access_token=pk.eyJ1IjoibWFwLWVneXB0IiwiYSI6ImNpdmxkMjl6bTA3c2YyeXBvNDJnZDlqZGMifQ.KQSizb18ILr6wri0cBcd2Q#6.3/31.283439/34.549652/1). Seems to be taking awhile for the MB api to update the tiles, but should update soon. Will close when it shows up.
