### ISSUE TITLE
Units not showing up in the legend

### ISSUE THREAD

**Issue by felskia** [map-egypt/map-egypt.github.io#287]
We had a ticket for this a while back but I don't see them anywhere. 

Just to clarify, if there is a unit variable in the backend it should appear in the legend. One indicator that has one but doesn't appear in the front-end is Cotton Crop Area - 2010. It is under "Other Indicator"

**Comment by nbumbarger** [comment]
@felskia I don't see where this would come from in the API. The only category attached to the overlays is e.g. "Sequential" (I didn't see a `Cotton Crop Area - 2010` overlay, but this was the case for 2011 and 2012). If this would require an API change, do you know what the name of the property is in the database? cc @kamicut
