### ISSUE TITLE
Other CSV issues

### ISSUE THREAD

**Issue by felskia** [map-egypt/map-egypt.github.io#288]
- For projects that have a KMI section, it doesn't appear on the spreadsheet

- For locations, can we distinguish or group the districts with the govenorates. Have separate columns or a way to organize a bit to make it more clear what is what?

**Comment by nbumbarger** [comment]
@felskia we can have a column of locations and a column of governorates. I don't think they can easily be grouped as belonging to one another without producing new data, so will that be confusing?

**Comment by felskia** [comment]
@nbumbarger So they go in the backend together. On the front-end it spits out something different?
