### ISSUE TITLE
Display of projects with Funding, Loans, Households, and Grants

### ISSUE THREAD

**Issue by nbumbarger** [map-egypt/map-egypt.github.io#292]
This project includes all 4 attributes when logged in, which don't appear to display properly
https://map-egypt.github.io/#/en/projects/8ab3f420-c74a-422a-9ff3-03be6918d367

**Comment by felskia** [comment]
@nbumbarger how does it appear on your monitor? Could you take a screenshot?

**Comment by nbumbarger** [comment]
@felskia On other pages with all 4 metrics, it's possible to set the monitor width just right for this to happen, but on [this page](https://map-egypt.github.io/#/en/projects/8ab3f420-c74a-422a-9ff3-03be6918d367) it seems like the numbers are just the right size for it to happen no matter the width.

![screen shot 2017-02-21 at 4 48 02 pm](https://cloud.githubusercontent.com/assets/9471488/23186644/d8e6b932-f855-11e6-940e-6ab6ad2e8cb8.png)
