### ISSUE TITLE
Set up the Yemen maps with the following shape files

### ISSUE THREAD

**Issue by felskia** [map-egypt/map-egypt.github.io#294]
[yem_bnd_adm2_a.zip](https://github.com/map-egypt/map-egypt.github.io/files/791291/yem_bnd_adm2_a.zip)
[yem_bnd_adm1_a.zip](https://github.com/map-egypt/map-egypt.github.io/files/791292/yem_bnd_adm1_a.zip)

**Comment by DylanMoriarty** [comment]
:+1: Make file built & functional in the Map Yemen Repo.
