### ISSUE TITLE
Districts Not Displaying Data

### ISSUE THREAD

**Issue by DylanMoriarty** [map-egypt/map-egypt.github.io#302]
We were looking at how Map Egypt handles datasets based on districts, and there currently only seems to be `Test District`. When you turn that layer on however, the data values don't appear to actually be hooked up.

<img width="1160" alt="screenshot 2017-03-03 13 54 28" src="https://cloud.githubusercontent.com/assets/9341928/23564714/04a2d4d2-0019-11e7-9f24-663429244e61.png">

@nbumbarger if this isn't already on your radar, I can check it out to see if it's a bug with the code returning the proper value or if that dataset's wonky.

**Comment by DylanMoriarty** [comment]
You can view the dummy district dataset in `SDG Goals -> Goal 15`

**Comment by nbumbarger** [comment]
I used a few tricks to optimize the districts a little while ago (680 KB > 160KB), and it seems to have broken the rendering. Fixed in #303
