### ISSUE TITLE
Donor numbers should be public

### ISSUE THREAD

**Issue by felskia** [map-egypt/map-egypt.github.io#311]
Can you change the below numbers to be public (you can see them without having to log in).

Also, for those that don't have numbers can we just have them say 0? So 0 Loans or 0 Grants.

**Comment by nbumbarger** [comment]
@felskia could you link to an example of donor numbers?

**Comment by felskia** [comment]
@nbumbarger sure. At the bottom of this screenshot

<img width="1076" alt="screen shot 2017-04-06 at 2 52 25 pm" src="https://cloud.githubusercontent.com/assets/5421566/24770658/ba681c08-1ad8-11e7-88dd-ae1a52bc310e.png">

**Comment by nbumbarger** [comment]
@kamicut this required an API change, PR at https://github.com/map-egypt/api/pull/32
