### ISSUE TITLE
Changing the date to be Month/Day/Year

### ISSUE THREAD

**Issue by felskia** [map-egypt/map-egypt.github.io#313]
All dates on the site

**Comment by drewbo** [comment]
@felskia can we not make them in that format? it's confusing for international audiences

**Comment by felskia** [comment]
@drewbo good catch. It's actually supposed to be the opposite and that was is currently confusing for the Egyptian folks. Which is the reason for the ticket.

**Comment by nbumbarger** [comment]
@felskia so the date should be YYYY/D/M?

**Comment by nbumbarger** [comment]
The date is currently set to render according to a users' location profile from their browser. People in the US should get m/d/yyyy while people with Arabic settings should get yyyy/m/d- but this will only work if their preferences are configured for it.

If it doesn't seem to be working for the audience, I could force the Arabic version of the site (or both versions) into always using yyyy/m/d.

**Comment by felskia** [comment]
@nbumbarger I would say always force it to this other format. No one in the US will be using this tool so having the day month year format will be better for the English speakers who will use it too.

**Comment by nbumbarger** [comment]
Sounds good, [this PR](https://github.com/map-egypt/map-egypt.github.io/pull/316) now changes the date in both views.
