### ISSUE TITLE
Number of projects in labels should match number of projects

### ISSUE THREAD

**Issue by felskia** [map-egypt/map-egypt.github.io#317]
Says 8 but there are many more on the map. 

<img width="594" alt="screen shot 2017-04-06 at 4 04 49 pm" src="https://cloud.githubusercontent.com/assets/5421566/24773432/2f301144-1ae3-11e7-8915-9691a5c19c62.png">

**Comment by nbumbarger** [comment]
@felskia it isn't a count; since all the black circles contain a different number in the middle, one of us arbitrarily chose to use 8 in the legend for a project pin.

**Comment by felskia** [comment]
@nbumbarger ah, it is very confusing though. Is there an easy way to make this a count?

**Comment by nbumbarger** [comment]
yep, there is. Added in https://github.com/map-egypt/map-egypt.github.io/pull/319.
