### ISSUE TITLE
Indicator Charts have different numbers depending on where you scroll over them

### ISSUE THREAD

**Issue by felskia** [map-egypt/map-egypt.github.io#318]
For unemployment 2006 in SDG goals (this is the only one I've noticed so far) if you roll over the bar chart towards the beginning of the bar it will say one number but if you roll away from the bar and then back over to it at the end of the bar, it will say a different number.

**Comment by nbumbarger** [comment]
The unemployment 2006 dataset contains multiple entries of the same record, each with different values, and the tooltip appears to pull them pseudo-randomly. The dataset will need to be fixed.
