### ISSUE TITLE
Problems with Recommendations based on project experience field

### ISSUE THREAD

**Issue by felskia** [map-egypt/map-egypt.github.io#329]
From Hagar: 

"the new addition "recommendations based on project experience" shows up on the project page as lorem ipsum even if there is nothing written there. (this will not be for all projects - mostly it will be used for closed/almost finished projects)"

@nbumbarger can you check this out?

**Comment by nbumbarger** [comment]
@felskia This shouldn't be the case- I don't see lorem ipsum on the deployed version of the site (it would appear under the SDS Pillars.
