### ISSUE TITLE
Indicators aren't showing up in Arabic

### ISSUE THREAD

**Issue by felskia** [map-egypt/map-egypt.github.io#345]
Right now it says 0 but there are a bunch. 

<img width="1048" alt="screen shot 2017-08-14 at 4 14 47 pm" src="https://user-images.githubusercontent.com/5421566/29289784-c746983e-810b-11e7-9d99-30c002529dab.png">

**Comment by dereklieu** [comment]
The API is not returning categories in arabic, @kamicut can you look to see why? Without Arabic categories there's no way to group the indicators. It also seems that the indicator names are coming in only English.

**Comment by kamicut** [comment]
@dereklieu I'm correcting the arabic names in the API now. By categories do you mean themes?
There are two types of "categories", the "type" of the indicator (sequential, diverging, categorical), and the "theme": "Economy", "Agriculture", which has the type "other", but also SDS and SDG indicators.

**Comment by kamicut** [comment]
@felskia @dereklieu 
The `labels.js` [label file](https://github.com/map-egypt/admin/blob/master/app/assets/scripts/utils/labels.js) that is in the admin does not contain the proper translation for themes. There are 2 missing translations for the SDS indicators, and no translations for SDG and "other" themes. We need these translations to render them in the frontend.

**Comment by kamicut** [comment]
@dereklieu I've added the missing translations to the labels file. Could you check if this is enough to continue work on this ticket?

**Comment by dereklieu** [comment]
@kamicut Not yet,  the `name_ar` and `description_ar` fields in this response are still null:

https://ifpri-egypt-silo.herokuapp.com/indicators

**Comment by kamicut** [comment]
@dereklieu that's a data entry mistake by the data team. There are some indicators (for example "Rice Production - 2010") that do have entries. Could we filter out the nulls?

**Comment by dereklieu** [comment]
It is filtering out the nulls, the problem is most of them are null, which is how we get the display at the top of this ticket.

@felskia it looks like this is data-entry related, the arabic names aren't getting inputted into the api somehow.

**Comment by felskia** [comment]
So this would be a @kamicut problem? We keep getting pinged by them since these little changes have taken us a while. Is there anyway the two of you can wrap these things up this week or beginning of next? 

@dereklieu

**Comment by dereklieu** [comment]
Closed #352
