### ISSUE TITLE
Add Arabic indicator translations to backend

### ISSUE THREAD

**Issue by felskia** [map-egypt/map-egypt.github.io#346]
Same image as the last but you can see with the buttons etc... Let me know if you need a translation of things. 

<img width="1048" alt="screen shot 2017-08-14 at 4 14 47 pm" src="https://user-images.githubusercontent.com/5421566/29289811-e2bf0e7a-810b-11e7-9fbf-0fcfbd50c5e0.png">

**Comment by dereklieu** [comment]
New translation text in https://github.com/map-egypt/map-egypt.github.io/pull/349, @hagareldidi can you update them? The new items are [here](https://github.com/map-egypt/map-egypt.github.io/pull/349/files#diff-3d3d7dd8a6ee38e7fbe9b3365b8a675eR51).

**Comment by felskia** [comment]
@dereklieu this is still an issue because it doesn't have the initial categories any more. I have the translations for them if you need them... Right now it just says other and I'm not sure where it's getting that from: 

<img width="1030" alt="screen shot 2017-10-23 at 2 58 09 pm" src="https://user-images.githubusercontent.com/5421566/31907798-e29003cc-b802-11e7-9325-521d9373ceef.png">

The first column on the right should be these (of course they're on the other side because this is in English :)

<img width="483" alt="screen shot 2017-10-23 at 3 01 01 pm" src="https://user-images.githubusercontent.com/5421566/31907847-07f87266-b803-11e7-9bbb-3fdc8bdee554.png">

**Comment by dereklieu** [comment]
@felskia those initial categories aren't translated. If you select the first dropdown, you'll see where they have translated the initial categories, but not the secondary categories.

<img width="912" alt="screen shot 2017-10-23 at 3 26 22 pm" src="https://user-images.githubusercontent.com/1590802/31909002-b9c51aa0-b806-11e7-902b-7fa7b039216c.png">

I can't make the initial translations appear if they aren't translated, so I added the "other" fall-back so they can at least see secondary translations.

There are 2 steps here to fix this:

1. Add the "other" translation in ar.yml
2. Add the indicator translations into the backend

cc @hagareldidi

**Comment by felskia** [comment]
@dereklieu we have them here though. We had already asked for them: https://docs.google.com/a/developmentseed.org/spreadsheets/d/142tBnsZO6I4B794L_QLCKsV9Bg9ESO7w2zCxldyKtL0/edit?usp=sharing

They're in the second tab.

**Comment by dereklieu** [comment]
Then there's some method to pull these translations into the back-end that hasn't been done. Not sure what that method is.

**Comment by kamicut** [comment]
I've had to re-save the data with the translations in the admin so that they get saved in the API. I am running into a rendering error on the frontend that @dereklieu is going to look into.

**Comment by dereklieu** [comment]
Rendering in #356
