### ISSUE TITLE
Indicator names show up in English on the map as well

### ISSUE THREAD

**Issue by felskia** [map-egypt/map-egypt.github.io#347]
<img width="1153" alt="screen shot 2017-08-14 at 4 18 21 pm" src="https://user-images.githubusercontent.com/5421566/29289900-3e6806e6-810c-11e7-9b81-5046ea4ac6fc.png">

**Comment by felskia** [comment]
@dereklieu this one is still happening too. Even though some of the names are translated in the backend.

**Comment by dereklieu** [comment]
After #356 you can add indicators in Arabic and they'll show up as Arabic everywhere.

If you add an Arabic indicator then toggle to English, the Arabic indicator will still be shown, and vice versa.

![demo2](https://user-images.githubusercontent.com/1590802/32740098-d341d22e-c86f-11e7-8adf-be369ea5c7e7.gif)

This isn't ideal but should be fine, the regular user will choose one language and won't be toggling back and forth.

**Comment by felskia** [comment]
@dereklieu this section isn't working for me in Arabic and also, these still show up in English...

<img width="1195" alt="screen shot 2017-11-13 at 1 54 12 pm" src="https://user-images.githubusercontent.com/5421566/32743412-4b7b7484-c87a-11e7-9971-8be3a80cdfdd.png">
