### ISSUE TITLE
Make map larger

### ISSUE THREAD

**Issue by felskia** [map-egypt/map-egypt.github.io#35]
On the map view of the project and indicators page please make the map much larger since this is the main view on this page. 

@ascalamogna assigned to you but let me know if it should be someone else. 

Thanks!

**Comment by ascalamogna** [comment]
@dereklieu I can adjust once toggling is implemented?

**Comment by dereklieu** [comment]
@ascalamogna does the size rely on toggles? I thought you could just do this via a css class.

**Comment by ascalamogna** [comment]
@dereklieu, no I was just thinking since we'll want to adjust the zoom level for this specific view and also it might be easier to figure out the best height once the stuff underneath isn't shown.

**Comment by dereklieu** [comment]
Gotcha. I was planning on working on map-related things tomorrow, so I can update you when I have something here.
