### ISSUE TITLE
SDG Goals not showing up under “Add and Filter projects” 

### ISSUE THREAD

**Issue by felskia** [map-egypt/map-egypt.github.io#355]
Also, noticed that the project status here isn't in arabic. Let me know if you need translations because we do have those. :)

<img width="1020" alt="screen shot 2017-10-23 at 3 50 13 pm" src="https://user-images.githubusercontent.com/5421566/31910011-11b13ca0-b80a-11e7-920f-fae73bc928e7.png">

**Comment by kamicut** [comment]
I applied the translations to the projects in the admin and this is now fixed.
