### ISSUE TITLE
More translations that need to be fixed

### ISSUE THREAD

**Issue by felskia** [map-egypt/map-egypt.github.io#362]
As going through the whole site and found that under the "Add and Filter Projects" button we have a bunch of text that is still in English. And we do have translations for them. Let me know if I should provide any of those translations here. 

Thanks!

**Comment by dereklieu** [comment]
@felskia @kamicut Arabic donor names aren't coming through the API. Here is the API data that I'm currently working with:

<img width="615" alt="screen shot 2017-11-19 at 2 26 11 pm" src="https://user-images.githubusercontent.com/1590802/32996307-d951fe44-cd35-11e7-80db-df7842a67b4a.png">

@kamicut if you could either add a `donor_name_ar` or make `donor_name` an object with `{ar: '', en: ''}`, either would work.

Pr #363 fixed the display of "On Time" and "Delayed."

**Comment by kamicut** [comment]
@dereklieu, this already works, there is a key called `donor_name_ar` which when filled in the backend will show up in the API. You can see it with this [public project](http://ifpri-egypt-silo.herokuapp.com/projects/13f7fd00-a53f-4566-a771-f9de5f73fc81)

**Comment by dereklieu** [comment]
@kamicut thanks, I missed that. Closed #365
