### ISSUE TITLE
Adjust width of buttons

### ISSUE THREAD

**Issue by felskia** [map-egypt/map-egypt.github.io#67]
On the comps the buttons are a little wider which I think was a pretty nice design choice. I would add this into the build. 

Also make sure that the notifications button in the footer is slightly wider and also that it has the same rollover pattern that the other buttons have.

**Comment by ascalamogna** [comment]
@felskia there's no button in the footer?

**Comment by felskia** [comment]
@ascalamogna ah, just the mail icon for the newsletter sign up. :)
