### ISSUE TITLE
Mapping questions

### ISSUE THREAD

**Issue by dereklieu** [map-egypt/map-egypt.github.io#7]
@felskia I have a few questions about the map.

1. Which admin level are we showing? In Teamwork I found one zip file with 4 admin levels (EGY0, EGY2-sinluxor, EGY2-withluxor2, and EGY3), and a separate shapefile with municipalities and districts. #6 includes them all in the processing pipeline, but it doesn't seem like they're all necessary.

2. How do indicators map to admin regions? In the indicator data I'm not seeing an admin id or anything like that, although I could have missed it.

3. What relationship will project locations have? Under `location` I found an array, which leads me to assume that a project can have more than one location. Does that mean if project `A` is at both location `x` and `y`, and project `B` is only at location `y`, then `x` will show 1 project, and `y` will show 2?

cc @drewbo @kamicut

**Comment by drewbo** [comment]
@dereklieu for 2, there should be a `sub_nat_id` column in all the indicators, I'm not as familiar with the shapefile but the last four digits of that column should match to something in the shapefile.

**Comment by felskia** [comment]
@dereklieu Hey! I emailed Hagar asking about the main shape file (before I saw this). Did you end up figuring out the other questions? If not I'd be happy to email her again. Let me know and I'll do it now or super early in the morning. 

Thanks!

**Comment by dereklieu** [comment]
Cool, yeah that should work out my first question, Drew answered my second question, and I'm still waiting on the third question, so maybe we should get some clarity on that one along with the shapefile info.
