### ISSUE TITLE
Add tooltip for status in KMI section

### ISSUE THREAD

**Issue by felskia** [map-egypt/map-egypt.github.io#71]
For every circle, have a tooltip or hover so you can know what the circle indicates. 

Also, separate these out into their own column. Right now it is too associated with Component and it's quite different.

**Comment by ascalamogna** [comment]
@dereklieu will need to add the tooltip, but if we're going to but this in a separate column, why don't we just do the dot and list the word 'delayed or 'on time' like we do throughout the rest of the site @felskia?

**Comment by felskia** [comment]
@ascalamogna yeah, I think that sounds good. :)
