### ISSUE TITLE
Project page header

### ISSUE THREAD

**Issue by felskia** [map-egypt/map-egypt.github.io#72]
- The delayed and last updated text is probably a little too close to the header now. 
- I'd move the two timelines closer together
- Give more space between the timeline and the tags
- Decrease the padding between the tags and the bottom of the page header. 

<img width="565" alt="screen shot 2016-12-01 at 3 01 05 pm" src="https://cloud.githubusercontent.com/assets/5421566/20810289/359e9c04-b7d7-11e6-8085-a060f40a7a54.png">

**Comment by ascalamogna** [comment]
@felskia is the screenshot what you are looking to do?

**Comment by felskia** [comment]
@ascalamogna yeah, that was just a thought. See what you think. Just wanted to relate the timeline a little more and then give other things a bit of space.
