### ISSUE TITLE
Better error for log in 

### ISSUE THREAD

**Issue by felskia** [map-egypt/map-egypt.github.io#94]
Tried to log in and got the below screenshot... This probably isn't something that is as important but is something we should probably look at. 
<img width="997" alt="screen shot 2016-12-04 at 2 47 59 pm" src="https://cloud.githubusercontent.com/assets/5421566/20868750/e1f299d2-ba30-11e6-98fb-3d1a1eb4f6e2.png">

**Comment by dereklieu** [comment]
@kamicut we should probably add `https://map-egypt.github.io/` to the list of allowed callbacks, as it doesn't automatically redirect to the devseed.com url. Can you do that?

**Comment by kamicut** [comment]
@dereklieu It's already there, is this still happening?

**Comment by dereklieu** [comment]
I haven't checked and was just going off of what I saw based on the error message @felskia posted.

**Comment by dereklieu** [comment]
If it's added then you should close this @kamicut
