### ISSUE TITLE
Incorrect Graph on Category Page

### ISSUE THREAD

**Issue by felskia** [map-egypt/map-egypt.github.io#98]
The first graph on the left, "Number of Projects per Category" These should be per category not per project. So how Health compares to Environment.

**Comment by dereklieu** [comment]
Not sure I understand, currently it's showing all the different categories on the Y axis and how many projects are in each category on the X axis, what should it be doing instead?

**Comment by felskia** [comment]
@dereklieu nevermind. I'm so sorry I was mixing up categories and SDS goals
